### ISSUE TITLE
Use "Issue" template for new issues

### ISSUE THREAD

**Issue by ner00** [libretro/scummvm#10]
This might be helpful and also incentivize users to be more cooperative by providing useful information from the get go when opening new issues. Here are a couple examples of what I mean:
- https://github.com/libretro/RetroArch/issues/new
- https://github.com/hrydgard/ppsspp/issues/new

**Comment by spleen1981** [comment]
9f1e2e583d9a5a8609a30e5edfc02b4c2414100b
