### ISSUE TITLE
ScummVM Crashes When Loading Games on New Nintendo 3DS XL

### ISSUE THREAD

**Issue by sonic65101** [libretro/scummvm#11]
## Description
When attempting to launch games (Starship Titanic purchased from Steam and Hi-Res Adventure 1 - Mystery House downloaded from the RetroArch Content Downloader), the console crashes.
### Expected behavior
The games launch normally.

### Actual behavior
The New Nintendo 3DS XL crashes, data abort.

### Screenshots
(Stack Dump is empty/blank.)
![20230114_202231](https://user-images.githubusercontent.com/24297223/213335847-dd4ce1c2-0b9a-4d3f-8e0d-3f3d2ebf44a3.jpg)

### Steps to reproduce the bug
1. Open RetroArch.
2. Select Load Content.
3. Navigate to the game's folder and select its .scummvm file.

### Version/Commit
[You can find this information under Information->Core Information / System Information]
- ScummVM core: v2.6.1.3-11-gf821940
- RetroArch: 1.14.0

### ScummVM game/engine
Game: Starship Titanic 1.00.42c (titanic-win), Engine: titanic

### Environment information
- Device: New Nintendo 3DS XL (North America)
- OS: 3DS OS (11.16)

### Additional context
[Add any other context about the problem here]

**Comment by spleen1981** [comment]
- If you load the core only from retroarch (without loading any game) and start it, can you reach ScummVM GUI?
Can you add the game from inside ScummVM GUI? If yes are you able to launch the game from the internal GUI?

- Can you provide [retroarch logs](https://docs.libretro.com/guides/generating-retroarch-logs/)?

- Can you test also with [this freeware game from scummvm site](https://downloads.scummvm.org/frs/extras/Beneath%20a%20Steel%20Sky/BASS-Floppy-1.3.zip)?

**Comment by sonic65101** [comment]
1. Yes. The ScummVM core launches to the GUI. Neither Hi-Res Adventure 1: Mystery House nor Starship Titanic were detected, however, Beneath a Steel Sky was detected, and could be launched without crashing both from ScummVM's GUI and RetroArch's Load Content option.
2. Log from trying to launch Hi-Res Adventure 1: Mystery House.
[retroarch.log](https://github.com/libretro/scummvm/files/10462471/retroarch.log)

**Comment by spleen1981** [comment]
The two engines from your test are not available in the 3DS build, as they are flagged as `highres`, which is not supported on this platform. This flag is coming from legacy libretro core.
This is the list of engines currently available in 3DS build:
```
access
agi
agos
ags
bbvs
cge
cge2
chewy
cine
cruise
versailles
director
draci
dragons
drascula
dreamweb
glk
gob
griffon
groovie2
hugo
hypno
illusions
kyra
lol
eob
lab
lure
made
mads
riven
myst
mystme
parallaction
queen
saga
sci
scumm
scumm_7_8
sherlock
sky
supernova
teenagent
tinsel
tsage
tucker
voyeur
foxtail
herocraft
xeen
```

However there are two points:

- The core should not crash that way if game is not recognized. This will be investigated.
- The `_highres=no` flag is not specified for 3DS in standalone ScummVM. I've have enabled it in [this build](https://git.libretro.com/libretro/scummvm/-/jobs/3056081/artifacts/download), can you test it?

**Comment by sonic65101** [comment]
I get a 404 page when trying to download the linked build.

**Comment by spleen1981** [comment]
> I get a 404 page when trying to download the linked build.

uploaded [here](https://drive.google.com/file/d/1sXr4ltfd3nmNnu-PH3WaFieMuUcPrj-z)

**Comment by sonic65101** [comment]
With that build, both Hi-Res Adventure #1: Mystery House and Starship Titanic are detected by ScummVM's Add Game option, but only Hi-Res Adventure #1: Mystery House launches. Trying to launch Starship Titanic displays the message "Could not find titanic.dat data file." and then closes ScummVM/RetroArch, returning to the 3DS Home menu.

**Comment by spleen1981** [comment]
The dat file is included in scummvm.zip, available from retroarch content downloader.
You can download for testing from here: https://github.com/scummvm/scummvm/blob/4bf45d922baaf68552c9936491d34361ffb467f2/dists/engine-data/titanic.dat

**Comment by sonic65101** [comment]
Starship Titanic also launches once the titanic.dat file is present.

**Comment by sonic65101** [comment]
Hi-Res Adventure #1: Mystery House runs fine. Starship Titanic starts out, just with audio stutter, but it slows down visually and audibly to the point of being unplayable once the ship crashes into the player character's house, though I think this is due to the 3DS's hardware.
