### ISSUE TITLE
Indiana Jones and the Fate of Atlantis isn't working anymore.

### ISSUE THREAD

**Issue by magicalnipperwiz** [libretro/scummvm#17]
## Description

When I try to launch the game "Indiana Jones and the Fate of Atlantis" (both floppy and CD) using Retroarch I got a message on scummvm saying "Could not find any engine capable of running the selected game".

The version of scummvm_libretro.dll that I'm using is 2.8.0git (Mar 15 2023)

The interesting bit is that if I change my scummvm_libretro.dll file to an old version that I have on my backup (2.1.1 - Dec 10 2022), the game works with no problem. What in fact makes sense since the game was working in the past.

Also, using the stand alone ScummVM emulator (2.7.0 - Feb 14 2023), the game also works with no problem.

### Expected behavior
I was expecting the game to work, it used to work.

### Actual behavior
I get a message saying "Could not find any engine capable of running the selected game"

### Steps to reproduce the bug
Just try to run the game.

### Version/Commit
2.8.0git (Mar 15 2023)

### ScummVM game/engine
atlantis
atlantis-1

### Environment information
Windows 11

### Additional context
It works on old dll and on stand alone ScummVM.
Other games are working, no problem there, just this one is faulty.

**Comment by spleen1981** [comment]
Can you try to edit the relevant game entry in `scummvm.ini` and add `engineid=scumm`?
In alternative you can open ScummVM GUI, remove the game from the list and add it again.

**Comment by magicalnipperwiz** [comment]
Yes, adding `engineid=scumm` works, both games. It adds a "splash screen" with the scumm version before the start of the game but this is no big deal for me.
