### ISSUE TITLE
Scummvm 2.8.0 run very slow

### ISSUE THREAD

**Issue by KamiLordus** [libretro/scummvm#19]
Many games run slow or very slow on the new scummvm 2.8.0 git version.
I tried removing all saved settings and reinstalling scummvm core but it doesn't help.
I also tried to change the dx11 driver to another one (vulcan, gl) but the result is the same.
The scrolling of the screen is not smooth, the cursor moves very slowly, and the game often does not respond to mouse clicks or responds with a long delay.
My pc:
Win 11 Pro, i7 8700k, rtx 3070ti
retroarch 1.15
Scummvm 2.8.0 git latest

Tested games:
Goblins 1-3 cd/floppy - run slow
Woodruff - run slow
Nightlong - run very slow
Neverhood - run slow
Phantasmagoria - run slow 

![Bez tytułu](https://user-images.githubusercontent.com/123302593/225976521-6049e6fd-1fbe-4afa-a9b5-e1381960bed5.png)

![Bez tytułu](https://user-images.githubusercontent.com/123302593/225977504-8b39255c-db9d-4167-93e5-a2ce2f4e0043.png)

And this is what it looks like in the YT video. Every game works the same way:
https://www.youtube.com/watch?v=6NL1c44Y6l0

**Comment by spleen1981** [comment]
fixed by c8b2cdb3815db26a7a500c034c1378e03db96f38

**Comment by spleen1981** [comment]
@KamiLordus can you check with the latest core available?

**Comment by KamiLordus** [comment]
@spleen1981 i tested many games (nightlong for example) and everything works very well, the cursor also works smoothly. Thank you very much for the fix.
