### ISSUE TITLE
Problem with changing themes

### ISSUE THREAD

**Issue by KamiLordus** [libretro/scummvm#19]
## Description
I downloaded scummvm.zip from here:
https://buildbot.libretro.com/assets/system/ScummVM.zip
and extracted to RA/system/scummvm/
In RA I loaded scummvm core and ran it. Then I set path to extra, and theme.
In the GUI/Theme tab, the only thing that is displayed is the builtin classic theme.
Can it be fixed somehow?

### Expected behavior
Changing the theme to something other than classic (e.g. modern)

### Actual behavior
Themes cannot be changed

### Screenshots
![1](https://user-images.githubusercontent.com/123302593/222717593-826cc473-3779-480d-9b3b-b3a8750e4e60.png)

![2](https://user-images.githubusercontent.com/123302593/222717615-c07ae049-b397-43de-a7c3-450460e55b14.png)

### Version/Commit
- ScummVM core: 2.7.01
- RetroArch: 1.14.0

### Environment information
- Device: I7 8700k, rtx 3070ti
- OS: Win 11 Pro

**Comment by spleen1981** [comment]
I guess it's a matter of giving the buildbot the time to get aligned, the new core version has just been issued.
You should wait and try to download again [ScummVM.zip](https://buildbot.libretro.com/assets/system/ScummVM.zip) later.

**Comment by KamiLordus** [comment]
Scummvm does not detect buildbot themes as of 2023.03.02.
I solved the problem by downloading themes from:
https://github.com/scummvm/scummvm/tree/master/gui/themes
I noticed that the THEMERC files from the zip archive are different from those from the liberto buildbot.

**Comment by spleen1981** [comment]
> Scummvm does not detect buildbot themes as of 2023.03.02

That was still aligned to the previous core version. If you check now there is the updated one.

The `scummvm.zip` file is not updated or uploaded manually, but it's built on the fly calling `make datafiles` from the core repo.

This is also the suggested way to build it locally.

**Comment by KamiLordus** [comment]
Thanks for your help and explanation. Now everything works fine.
