### ISSUE TITLE
Cursor does not move (Scummvm 2.8.0 git 73fed809)

### ISSUE THREAD

**Issue by KamiLordus** [libretro/scummvm#21]
Sorry for another bug report but cursor does not move. The cursor can only be moved in fast forward mode (space).
Games are 60fps but run like 1fps.
Same thing when loading scummvm core to add a new game for example. The cursor works with a giant delay and you can't navigate in the menu.

This is how it works on the video:
https://www.youtube.com/watch?v=FEdBO_Kg8vA

**Comment by spleen1981** [comment]
can't reproduce this with BASS. are you sure you are at 73fed809?

**Comment by KamiLordus** [comment]
My version is 73fe809 - the latest download from RA. Is it a bug that on github it is 73fe80 (without 9) ?
I tried to remove retroarch settings, and redownload scummvm but still the same. The cursor responds to movement with a gigantic delay, and when it moves slightly, it slows down the game itself.
The problem affects every game, and the scummvm core itself.
The display driver is DX11.

![Bez tytułu](https://user-images.githubusercontent.com/123302593/227232402-d9de4c81-a073-4817-bdcb-ff36b0741afd.png)

**Comment by spleen1981** [comment]
same issue with glcore?
can you provide RA debug logs?

**Comment by KamiLordus** [comment]
I tested DX11, Gl, Gl core, and vulcan - they all work the same.
I created a retroarch.log - I hope I did it right.
[retroarch.zip](https://github.com/libretro/scummvm/files/11052503/retroarch.zip)

**Comment by i30817** [comment]
Works fine here, although i'm in linux. It's ironic that as soon as the mouse cursor was fixed in wayland it got broken in windows, but that's unrelated. Might it be the changes done for audio latency?

**Comment by KamiLordus** [comment]
I just finished testing the latest scummvm core on an old and slow laptop (Windows 10, hdd).
Thanks to that I have some interesting information:
On an old laptop with RA 1.14, the cursor was a bit faster. Although far from smooth scrolling.
After installing RA 1.15, the cursor does not react at all (about 1 fpf, the same as on a pc with rtx 3070ti).
I managed to find an older version of scummvm (v2.6.1.4-7-g1f9f256) and this works perfectly, scrolling is super smooth.
In addition, Dremweb which does not work at all with the latest core version 2.6.1.4 works perfectly.

**Comment by ToniBC** [comment]
Yes, the same thing happens to me with the mouse, the other previous versions work without problems. It all seems to be related to the latest fix in timing from the looks of it. You can only control the mouse with fast forward, but the core slowed down a lot.

**Comment by spleen1981** [comment]
should be fixed by 71ad316f1fc51e4beaa5fd3ed1814c849b245efc

**Comment by spleen1981** [comment]
@KamiLordus is this confirmed to be working now?

**Comment by KamiLordus** [comment]
I just downloaded the latest version and the problem is solved.
Thanks.
