### ISSUE TITLE
Tag/branch for each official release

### ISSUE THREAD

**Issue by DrUm78** [libretro/scummvm#24]
Hey, great work on doing this repo so that we can enjoy the latest ScummVM upstream changes.

One question though: would it be possible to keep the same commit structure and tags as the original repo so we know when we can release an official build for a specific system and from an identified commit? I mean, for instance, this commit is the last one for branch-2-7-0 and tag v2.7.0 on the upstream repo but does not exist on your repo (it does but does not belong to any branch): https://github.com/libretro/scummvm/commit/727f8f8cb9b1e71510d0ced6fb4de596de28c05f.

Thanks!

**Comment by spleen1981** [comment]
Why shouldn't the upstream `scummvm/scummvm` repo be used directly for the purposes above?
`master` branch here is a plain upstream clone without additional commits.
This fork is used mainly as a staging area for modifications before pushing upstream, to feed CI/CD and buildbot and to collect issues.
Anyway note that libretro core has been merged upstream after the latest official release (2.7.0), so you need to wait for the next one,
