### ISSUE TITLE
Kyra.dat and Others .dat Not Working

### ISSUE THREAD

**Issue by ToniBC** [libretro/scummvm#26]
With the last update, it returns to give errors in various game engines, saying that they are corrupt or not correct.

This from the updater / content of the cores and from the repository to which it is linked.

Thank you.

**Comment by KamiLordus** [comment]
I tested the Legend of Kyrandia CD and Floppy version and I don't see any problem (Win 11).
Try updating the scummvm files:
online updater / core system files downloader / scummvm.zip

**Comment by ToniBC** [comment]
Sorry, my fault, for some reason, the path is modified and it was pointing wrong to the extras folder. 

Everything correct, sorry for the inconvenience and thank you very much.
