### ISSUE TITLE
Bizarre Adventures of Woodruff and the Schnibble of Azimuth - glitchy graphic after update

### ISSUE THREAD

**Issue by KamiLordus** [libretro/scummvm#29]
After one of the latest updates, Woodruff is quite broken:

Start screens (logo, intro etc) are very enlarged.
![1](https://user-images.githubusercontent.com/123302593/233800345-33bc1816-13e3-4161-9ea7-b0319e027566.png)

![Bez tytułu](https://user-images.githubusercontent.com/123302593/233800358-2142d021-f7a6-47ad-bdd5-bacb992accbb.png)

![2](https://user-images.githubusercontent.com/123302593/233800367-b30e2a47-0286-4b77-9f9a-94134350e6c2.png)

The main character is not seen in the first scene when he leaves the house. And on the right side of the screen you see some weird graphical glitches.
![5](https://user-images.githubusercontent.com/123302593/233800444-92cd43d2-c13d-44fc-8392-97d53754482a.png)

The transition between locations makes the main character enlarged.
![6](https://user-images.githubusercontent.com/123302593/233800581-a225e453-177d-4b26-8fd3-81e023c661bd.png)

I will add that sometimes after a few restarts of the game, the intro is displayed normally. However, this does not fix bugs later in the game.
I tested the English (woodruff-gb) and Polish (woodruff-pl) versions

RA 1.15
Win 11

**Comment by spleen1981** [comment]
- is it working with latest (daily build) stand alone scummvm?
- do you have a working commit reference for the core?

**Comment by KamiLordus** [comment]
At the moment I don't have standalone scummvm, only (latest) in retroarch. Today or tomorrow I will try to download standalone scummvm and test it. The game was working perfectly on Retroarch until about a week ago.

"do you have a working commit reference for the core"
I'm sorry but I don't quite understand what exactly it means.
core settings? (all by default).
Retroarch settings are forced 4:3 aspect ratio, and dx11 driver everything else is default.
scummvm launcher also all on default

**Comment by KamiLordus** [comment]
I will add that the Goblins 3 ONLY CD version also has a very similar bug (no company name, and graphical glitches in the intro).
The whole series also has one more bug which will be described in another report.
![1](https://user-images.githubusercontent.com/123302593/233802890-af15f03c-0e40-44ec-a2c8-b9e63c54e1ec.png)

![2](https://user-images.githubusercontent.com/123302593/233802891-39587347-06e2-4dc6-8326-c1c8739b9b71.png)

Also like Woodruff restarting the game (maybe but it's random) makes the intro and subtitles display correctly.

**Comment by spleen1981** [comment]
I mean do you have the exact previous core version which was working?

**Comment by KamiLordus** [comment]
I managed to download versions 36e8aa19 (1 day ago). There is no problem with the graphics in both Woodruff and Goblins 3 in this version.

**Comment by spleen1981** [comment]
> I managed to download versions 36e8aa19 (1 day ago). There is no problem with the graphics in both Woodruff and Goblins 3 in this version.

This is the current master, does it mean the issue is already solved?

**Comment by KamiLordus** [comment]
Unfortunately not.
The latest one that retroarch downloads is 74b91f3b and it contains all the problems I described.

**Comment by spleen1981** [comment]
> Unfortunately not. The latest one that retroarch downloads is [74b91f3](https://github.com/libretro/scummvm/commit/74b91f3bf3c970ef193960636e510cffc950d892) and it contains all the problems I described.

Yes, 36e8aa196f9b3c64caaec29d4d6b055dcfbd11c0 is current commit of `staging_master` branch indeed.
It looks there have been recent changes in gob engine upstream which caused regressions here.

**Comment by KamiLordus** [comment]
From what I can see (scummvm wiki) all games are gob engine:
Woodruff
Gobliins CD
Goblins 2CD
Goblins 3 CD
And they all have a problem in RA. I hope this can be fixed.

**Comment by spleen1981** [comment]
can you check if issue is solved with latest master 9a861391c861a1d4103df4e28444a375e885da72?

**Comment by KamiLordus** [comment]
Fixed. Thank you very much.
