### ISSUE TITLE
EMUELEC Makefile.common:503: *** Configuring ScummVM engines failed.  Stop.

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/scummvm#3]
Hello

I'm trying to compile against EMUELEC 4.6 in an odroid n2+ sbc and I'm getting tthe error message Makefile.common:503: *** Configuring ScummVM engines failed.  Stop.

For building it. I did a simple make or make platform=armv8 and same message. Pls can you help?

thx

~/EmuELEC$ PROJECT=Amlogic-ce DEVICE=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC ./scripts/build scummvm
CLEAN      scummvm
    *      Removing /home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/scummvm-fe6ca7910cef5ba4e5c71ba22eac7b8b58ff970a ...
    *      Removing /home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/qa_checks/scummvm-* ...
UNPACK      scummvm
tar: .gitignore: time stamp 2023-01-05 01:24:57 is 2144.599219439 s in the future
tar: .gitlab-ci.yml: time stamp 2023-01-05 01:24:57 is 2144.599130466 s in the future
tar: .gitmodules: time stamp 2023-01-05 01:24:57 is 2144.599093053 s in the future
tar: LICENSE: time stamp 2023-01-05 01:24:57 is 2144.598786944 s in the future
tar: Makefile: time stamp 2023-01-05 01:24:57 is 2144.59852295 s in the future
tar: Makefile.common: time stamp 2023-01-05 01:24:57 is 2144.598423164 s in the future
tar: README.md: time stamp 2023-01-05 01:24:57 is 2144.598379013 s in the future
tar: bundle_datafiles.sh: time stamp 2023-01-05 01:24:57 is 2144.598055422 s in the future
tar: config.mk.engines.lite: time stamp 2023-01-05 01:24:57 is 2144.598001709 s in the future
tar: configure_engines.sh: time stamp 2023-01-05 01:24:57 is 2144.597963781 s in the future
tar: ctr.mri: time stamp 2023-01-05 01:24:57 is 2144.597927214 s in the future
tar: dist/README.md: time stamp 2023-01-05 01:24:57 is 2144.597602827 s in the future
tar: dist/Roland_SC-55.sf2: time stamp 2023-01-05 01:24:57 is 2144.546452715 s in the future
tar: dist: time stamp 2023-01-05 01:24:57 is 2144.546335346 s in the future
tar: jni/Android.mk: time stamp 2023-01-05 01:24:57 is 2144.545838698 s in the future
tar: jni/Application.mk: time stamp 2023-01-05 01:24:57 is 2144.545799531 s in the future
tar: jni: time stamp 2023-01-05 01:24:57 is 2144.545789662 s in the future
tar: libnx.mri: time stamp 2023-01-05 01:24:57 is 2144.545764915 s in the future
tar: libretro-common: time stamp 2023-01-05 01:24:57 is 2144.545580479 s in the future
tar: libretro-deps: time stamp 2023-01-05 01:24:57 is 2144.545428965 s in the future
tar: link.T: time stamp 2023-01-05 01:24:57 is 2144.545398511 s in the future
tar: lite_wiiu.mri: time stamp 2023-01-05 01:24:57 is 2144.545372998 s in the future
tar: scummvm: time stamp 2023-01-05 01:24:57 is 2144.545211931 s in the future
tar: src/config.h: time stamp 2023-01-05 01:24:57 is 2144.544729088 s in the future
tar: src/libretro-fs-factory.cpp: time stamp 2023-01-05 01:24:57 is 2144.544689827 s in the future
tar: src/libretro-fs-factory.h: time stamp 2023-01-05 01:24:57 is 2144.544665256 s in the future
tar: src/libretro-fs.cpp: time stamp 2023-01-05 01:24:57 is 2144.544632421 s in the future
tar: src/libretro-fs.h: time stamp 2023-01-05 01:24:57 is 2144.544603987 s in the future
tar: src/libretro.cpp: time stamp 2023-01-05 01:24:57 is 2144.544566006 s in the future
tar: src/libretro_core_options.h: time stamp 2023-01-05 01:24:57 is 2144.544194852 s in the future
tar: src/libretro_core_options_intl.h: time stamp 2023-01-05 01:24:57 is 2144.543642591 s in the future
tar: src/libretro_os.cpp: time stamp 2023-01-05 01:24:57 is 2144.543309505 s in the future
tar: src/os.h: time stamp 2023-01-05 01:24:57 is 2144.543263796 s in the future
tar: src/portdefs.h: time stamp 2023-01-05 01:24:57 is 2144.543239682 s in the future
tar: src/retro_emu_thread.cpp: time stamp 2023-01-05 01:24:57 is 2144.543213502 s in the future
tar: src/retro_emu_thread.h: time stamp 2023-01-05 01:24:57 is 2144.543190094 s in the future
tar: src/surface.libretro.h: time stamp 2023-01-05 01:24:57 is 2144.542925746 s in the future
tar: src: time stamp 2023-01-05 01:24:57 is 2144.542903253 s in the future
tar: tmp/libFLAC/share/win_utf8_io/win_utf8_io.c: time stamp 2023-01-05 01:24:57 is 2144.54222265 s in the future
tar: tmp/libFLAC/share/win_utf8_io: time stamp 2023-01-05 01:24:57 is 2144.542002524 s in the future
tar: tmp/libFLAC/share: time stamp 2023-01-05 01:24:57 is 2144.541977978 s in the future
tar: tmp/libFLAC: time stamp 2023-01-05 01:24:57 is 2144.541971196 s in the future
tar: tmp: time stamp 2023-01-05 01:24:57 is 2144.541965653 s in the future
BUILD      scummvm (target)
    TOOLCHAIN      make
Platform is unix 32bit
Configuring ScummVM engines...
sed: can't read configure: No such file or directory
Makefile.common:503: *** Configuring ScummVM engines failed.  Stop.
FAILURE: ./scripts/build scummvm during make_target (package.mk)
*********** FAILED COMMAND ***********
make
**************************************

**Comment by spleen1981** [comment]
Did you clone also the submodules? You can check `scummvm` subfolder, if it is empty you did not.
When you `git clone` this core, you need the `--recursive` flag.
Also better `platform=armv8` for performance in your case.

**Comment by Kelvfimer** [comment]
Cool @spleen1981 that was the issue didn't take in account the recursiveness. Thx so much and thx for the great work :) . I hope somebody could port Yabasanshiro to libretro again.
