### ISSUE TITLE
Halls of The Dead - Faery Tale Adventure II bug

### ISSUE THREAD

**Issue by Urthaug78** [libretro/scummvm#31]
Hi to all,

just to notify that the new supported Halls Of The Dead doesn't work, crashes Retroarch once in-game...

Tested under Windows 7 64-bit, Retroarch 1.15.0, libretro-scummvm 2.8.0git...

P.S. Sorry for my bad english

**Comment by spleen1981** [comment]
Can you provide RetroArch logs with DEBUG level set both for frontend and cores?

**Comment by Urthaug78** [comment]
Here is debug level log, if i i've done it correctly... 

[retroarch.log](https://github.com/libretro/scummvm/files/11308065/retroarch.log)

**Comment by spleen1981** [comment]
I've submitted the PR https://github.com/scummvm/scummvm/pull/4984 upstream, it can be tested with the `fix_saga2_infinite_loop` branch.

**Comment by spleen1981** [comment]
fix merged fd32607b9fa122c2ade5871a99371d2201b10cf0
