### ISSUE TITLE
the commit 2fb2e4c551c9c1510c56f6e890ee0300b7b3fca3 disappeared

### ISSUE THREAD

**Issue by VergilGao** [libretro/scummvm#32]
https://github.com/libretro/Lakka-LibreELEC/blob/Lakka-v4.x/packages/emulation/libretro-scummvm/package.mk

when i try to build the lakka-v4.x, the build function download code from `5873ee968885676902df2c6765f0f520680ba80e` instead of `2fb2e4c551c9c1510c56f6e890ee0300b7b3fca3`
and it throw an error :
```
make: *** [/home/builder/retroarch-kodi-addon-CoreELEC/Lakka-LibreELEC/build.Lakka-AMLGX.arm/build/scummvm-5873ee968885676902df2c6765f0f520680ba80e/backends/platform/libretro/Makefile.common:195: scummvm.zip] Error 127
make: *** Waiting for unfinished jobs....
make: Leaving directory '/home/builder/retroarch-kodi-addon-CoreELEC/Lakka-LibreELEC/build.Lakka-AMLGX.arm/build/scummvm-5873ee968885676902df2c6765f0f520680ba80e/backends/platform/libretro'
FAILURE: ./scripts/build scummvm during make_target (package.mk)
```

**Comment by spleen1981** [comment]
Not an issue: this core has been revamped from scratch first, and then re-adapted to be merged upstream, so commit history has been erased 2 times in the last months.
So the commit above has not been removed, it does just not belong to current repo.
