### ISSUE TITLE
New bugs

### ISSUE THREAD

**Issue by KamiLordus** [libretro/scummvm#33]
Gobliins 2 - title screen freezes the game, and RetroArch.
Woodruff - the entire intro, subtitles, transitions between locations scroll super fast.
Goblins 3 - same situation
Prince and Coward - same situation
DreamWeb (floppy and CD version) - same situation
Discworld 2 - same situation
TeenAgent - same situation
Future Wars - The very beginning of the game - the company logo, subtitles scrolls ultra fast.
Gabriel Knight 2 - close game = retroarch crash

And probably many more, but I don't have all the games on scummvm and checking the ones I listed takes a lot of time.
It looks like turning on the space bar (super fast scrolling) while playing on Retroarch.
Pressing the space bar makes no difference. Space bar (fast scrolling) worked quite poorly on scummvm, now not at all.

One request. Could you improve the cursor movement for Woodruff ? (I use pc mouse, or xbox one controller). In this particular game, the cursor has stuttering when moving.
And one question: is there a chance to add a stable 2.7 version of scummvm to RA? Version 2.8 of git could stay around for people who want to see the latest fixes. However, playing on version 2.8 is quite difficult. Today the game works fine, tomorrow update and new problems.

Ps.Unfortunately, I don't have any of the previous versions without errors and I don't see any older than 1 day for download.

edit:
I've noticed that the allow timing inaccuracies option fixes many of the listed issues. However, not all of them, because many games still run too fast.
DremWeb - intro still runs way too fast.
Gobliins 2 / Woodruff - loading screens are too fast. Previously, they lasted longer and you could see pictures from the game on them.
Prince and Coward - dialogues in the intro are cut off

**Comment by spleen1981** [comment]
should be fixed with 842a52fd42c23d0290af768bf2593634008467ba

**Comment by spleen1981** [comment]
> And one question: is there a chance to add a stable 2.7 version of scummvm to RA? Version 2.8 of git could stay around for people who want to see the latest fixes. However, playing on version 2.8 is quite difficult. Today the game works fine, tomorrow update and new problems.

Nope, libretro buildbot takes only the default branch, which needs to be the master of course.
Also 2.7.0 branch does not include libretro core yet, it would need to be backported, but does not make any sense.
If you want to stick with an official release you should wait for 2.8.0 and build the core manually from [scummvm/scummvm](https://github.com/scummvm/scummvm) repo. Of course you will find there all the bugs not catched up before in the master branch :)

I think the closest think you can do is lock the core for updates (or backup it) when the 2.8.0 will be released (next build will be marked as 2.9.0-git), or when you think a version is stable enough, and store it somewhere.

**Comment by KamiLordus** [comment]
It's a very good suggestion :) Unfortunately, I always forget about it :) - I have to change it.
But at least the core has a beta tester :D

**Comment by KamiLordus** [comment]
Version 842a52f seems to have fixed the performance issues.
Great job, thanks for the fix.
