### ISSUE TITLE
Eye Of The Beholder I & II mouse stuttering, games slightly slow

### ISSUE THREAD

**Issue by Urthaug78** [libretro/scummvm#34]
Hi, i've noticed that the Beholder saga is slightly slow with mouse stuttering in 2.8.0...

The games run flawlessly in 2.6.1...

**Comment by spleen1981** [comment]
which platform?

**Comment by spleen1981** [comment]
On Windows it seems to work good with very smooth mouse cursor movement, are you sure you are on latest master?

**Comment by Urthaug78** [comment]
I'm on an old nettop windows based i use to rough test games on the fly...

I've downloaded the last updated core but the problem persists, probably the 2.8.0git is more cpu demanding...

In the old 2.6.1 version all is fine...

**Comment by Urthaug78** [comment]
Tested on different versions of Retroarch (1.15 and 1.13)...

**Comment by Urthaug78** [comment]
Also in plain ScummVM 2.7.0 the same games run ok...

**Comment by spleen1981** [comment]
If it's old hardware you may try to enable `Allow Timing Inaccuracies` in Core Options > Timing and set `Frameskip Mode` to `Auto` in Core Options > Frameskip.

**Comment by Urthaug78** [comment]
Allow timing inaccuracies did the job...
