### ISSUE TITLE
on Miyoo Mini Plus - after QUIT it should fall back to OnionOS instead of RetroArch

### ISSUE THREAD

**Issue by Benman2785** [libretro/scummvm#36]
Hi,

i use Miyoo Mini Plus with Onion OS - it comes with RetroArch

after playing in ScummVM and when i "quit" the game (even if i returned to launcher before ) i get back to RetroArch Menu and have to manually "quit RetroArch"

is there a way to force that automaticly so that i fall back into OnionOS :)

**Comment by spleen1981** [comment]
Core behaviour is exactly as intended, on exit it goes back to the frontend.
What you are looking for is retroarch option "Quit on Close Content" (Settings > User Interface)
