### ISSUE TITLE
Question about .scummvm files starting the Launcher

### ISSUE THREAD

**Issue by Benman2785** [libretro/scummvm#37]
Hi,

Miyoo Mini Plus uses this launch.sh to launch the games from .scummvm files:

> #!/bin/sh
> echo $0 $*
> progdir=`dirname "$0"`
> homedir=`dirname "$1"`
> rompath="$1"
> 
> echo "Running game : \"$rompath\""
> 
> # set CPU performance mode
> echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
> 
> # disable audioserver to gain some MB of ram
> /mnt/SDCARD/.tmp_update/script/stop_audioserver.sh
> 
> # Running retroarch (ScummVM will be launched with the argument contained in the .target file).
> cd /mnt/SDCARD/RetroArch/
> HOME=/mnt/SDCARD/RetroArch/ $progdir/../../RetroArch/retroarch -v -L  $progdir/../../RetroArch/.retroarch/cores/scummvm_libretro.so "$rompath"

what i try to do is launch ScummVM Launcher from a .scummvm file (tried it with scumm or scummvm as ID - not working)

how to do that?

**Comment by spleen1981** [comment]
You can't launch ScummVM GUI through `.scummvm` files, they have a different purpose.
Check [here](https://docs.libretro.com/library/scummvm/#running-a-game) what's the use of `.scummvm` files.

To launch ScummVM GUI from CLI you can just use the `-L` option without specifying any rom/game (hence you just remove the last `"$rompath"` in the script above).

**Comment by Benman2785** [comment]
main problem is that i cant run an sh from the xml file that creates the filelist in the gui of MiyooOS

yet will try some stuff on sunday - because i dont have time earlier

**Comment by spleen1981** [comment]
That is not an issue related to scummvm core anyways, retroarch needs to be launched from command line with parameters above to launch directly a core.
