### ISSUE TITLE
Longest Journey - retroarch crash after clicking new game

### ISSUE THREAD

**Issue by KamiLordus** [libretro/scummvm#39]
After pressing new game, the game crashes retroarch.
It happens randomly. Sometimes the game will launch correctly. If we have save/autosave and want to start over then RA will crash.
Interestingly, when autosave loads and exits to the menu, the game should start fine (new game).

My version of The Longest Journey is from GOG.
Win 11, RA 1.15

**Comment by spleen1981** [comment]
can you provide RA log with DEBUG level set?

**Comment by KamiLordus** [comment]
[retroarch.log](https://github.com/libretro/scummvm/files/11872279/retroarch.log)

When launching The Longest Journey

**Comment by spleen1981** [comment]
is this a log including the crash?

**Comment by KamiLordus** [comment]
I'm not sure. But I guess not. The game doesn't crash retroarch, it just freezes it completely. To close RA you need to use alt del ctrl.

**Comment by spleen1981** [comment]
> I'm not sure. But I guess not. The game doesn't crash retroarch, it just freezes it completely. To close RA you need to use alt del ctrl.

ok, we need a log covering this situation.

**Comment by KamiLordus** [comment]
When I use alt + ctrl + del to close retroarch the log looks like this 
[retroarch.log](https://github.com/libretro/scummvm/files/11878125/retroarch.log)

Interestingly, I still have the core version of scummvm c6cb7c3 and this launches the game without any problem.

**Comment by spleen1981** [comment]
can you test [longest_journey_crash ](https://git.libretro.com/libretro/scummvm/-/tree/longest_journey_crash) branch?

**Comment by KamiLordus** [comment]
Unfortunately the same.
However, I noticed that the allow timing inaccuraties option fixes this problem.
So I close this issue.
