### ISSUE TITLE
Wii u virtual keyboard

### ISSUE THREAD

**Issue by alfonsico** [libretro/scummvm#40]
Sorry if it's dupe

I can't begin Monkey 2 game cause it need enter some numbers as a key

Is there a way to virtualize a keyboard in Wii U?

Thanks

**Comment by spleen1981** [comment]
Virtual keyboard is already available, just press select button. Note that you need [data files](https://github.com/libretro/scummvm/tree/master/backends/platform/libretro#data-files-and-themes) installed to have the virtual keyboard working.
Also the right analog stick will emulate numeric pad direction keys, which would make the job for your case.

**Comment by alfonsico** [comment]
Thanks I could enter number with the trick
I will investigate about data file for figure out the path where I need to save them, I would like see the virtual keyboard in Wii U

Is there any chance to implement a “point and action” with Gamepad touch screen. You can point at but the action are with buttons

Second idea. Is it possible use a wiimote as a pointer with IR?

**Comment by spleen1981** [comment]
The datafiles can be downloaded from [here](https://buildbot.libretro.com/assets/system/ScummVM.zip) (or through retroarch online updater) and must be placed in retroarch system folder (the one containing `scummvm.ini`) under `scummvm` subfolder.

> Is there any chance to implement a “point and action” with Gamepad touch screen. You can point at but the action are with buttons

The hardware support is provided by the libretro API, if there is a supported touchpad tap input I think you should see it in retroarch input menu and customize the relevant retropad button used for mouse click in scummvm to this tap input.
If there is no hardware support in the API there is nothing that can be done from within the core.

> Second idea. Is it possible use a wiimote as a pointer with IR?

I remember that was working on WII, not sure if on wiiu it's the same.
However same as previous point regarding hardware support, if it's there it will work out of the box, as support for `RETRO_DEVICE_POINTER` is already implemented in the core.

**Comment by spleen1981** [comment]
Closing this as OP was [answered](https://github.com/libretro/scummvm/issues/40#issuecomment-1676131040) (though the right analog stick part is superseded, with current retropad mapping settings number keys can be set up as needed).
