### ISSUE TITLE
Controller mapping problem

### ISSUE THREAD

**Issue by KamiLordus** [libretro/scummvm#41]
Hi @spleen1981 I tested the latest bild 1dbb8cf9 and found one problem. When using a controller (Xbox One), the right mouse button does not work.
By default, the right mouse button is assigned to the R button on the controller. Assigning another button as the right mouse button also does not change anything.
I will add that when using a mouse, the left and right buttons work properly.

RA 1.16
Windows 11

**Comment by spleen1981** [comment]
fixed by a56c2b8
