### ISSUE TITLE
[iOS] The core crashes launching COMI and Full Throttle

### ISSUE THREAD

**Issue by illando** [libretro/scummvm#42]
Using the latest RA daily build  (1.16.0 of 2023-09-10) ScummVM 2.80.git., the app crashes playing these 2 games:

- Full Throttle on launch
- COMI After the CMI logo animation (the monkeys are listening). Not happening if you load a precedent save state instead of choosing difficult and starting a new game.

I can confirm this is not happening on the same RA version for MacIntel and Firestick so it should be iOS related.

**Comment by spleen1981** [comment]
- Is it working on stand alone [ScummVM daily build](https://www.scummvm.org/downloads/#daily)?
- Please provide RetroArch logs with DEBUG level set both for frontend and cores

**Comment by illando** [comment]
Hi @spleen1981 I'm sorry but this is too technical for me. I'm not a developer, I'm just downloading the RA ipa file from their website and sideloading it on my iphone using Altserver on a non-jailbroken device.
All i can do is download the stable IPA file from ScummVM website (2.7.1  iOS 9+ package .ipa (signed) last update: 2023-07-17) and confirm COMI and Full Throttle runs perfectly.

**Comment by illando** [comment]
@spleen1981 Here are the two log files you asked for:
COMI:
[COMI.log](https://github.com/libretro/scummvm/files/12646918/COMI.log)

Full Throttle:
[Full Throttle.log](https://github.com/libretro/scummvm/files/12646923/Full.Throttle.log)

**Comment by spleen1981** [comment]
Nothing in these logs, but I think something is going wrong [here](https://github.com/libretro/scummvm/blob/efa6ac88b2b57ee6083c6f46ec3e4cbf1dfa0688/engines/scumm/smush/smush_player.cpp#L1187).
We will need more detailed logs to understand what's the problem, a retroarch log from this [debug build](https://git.libretro.com/libretro/scummvm/-/jobs/4191129/artifacts/download) would be useful, as I can't test myself.

**Comment by i30817** [comment]
A while ago upstream scummvm reverse engineered the subtitles in 'videos' format (in had timing information inband I think).

Might be older scummvm data files, or something. Err, I dunno

**Comment by spleen1981** [comment]
fixed by 3fffa3de006a72ebe113a50b2b006b39e89b8aaf
