### ISSUE TITLE
Grim Fandango cannot be played on Anbernic or Retroid Consoles, controls cannot be mapped

### ISSUE THREAD

**Issue by arnaullv** [libretro/scummvm#45]
Grim Fandango cannot be played on Anbernic (RG405m or R505) or Retroid, Android Consoles because the controls cannot be mapped.
The controls are not detected when trying to map them on the scummvm options.

This issue doesn't happen using the Scummvm apk for Android.

**Comment by spleen1981** [comment]
What do you mean controls are not detected? There is no detection, core option just assign a key/ function to a retropad key.
Does your device use retropad or what?

**Comment by spleen1981** [comment]
Maybe you can share your retroarch.cfg and retroarch log with debug level set.

**Comment by arnaullv** [comment]
Just extracted the log.
I just ran retroarch scummvm module, mapped controls (with the lower right joystick, the other controls cannot be mapped at all because both control the mouse) and ran the game. Even with the controls mapped, the character cannot move or does any action when using the mapped buttons.
Also quite a few times I receive the android system message "wait the app to respond or close the app"

I tried to find retroarch.cfg but cannot find it, maybe it's related RG405M is an Android 12 device, and it's not accesible.

Again with the native Scummvm apk Grim fandango runs perfect even without mapping any control.
I think it might be related to that most Scummvm games use mouse and this one does not.

[retroarch__2023_11_03__17_15_11.log](https://github.com/libretro/scummvm/files/13252417/retroarch__2023_11_03__17_15_11.log)

**Comment by spleen1981** [comment]
It looks like you have a wrong mapping, movement for this game is not controlled with UP/DOWN/LEFT/RIGHT, but with NUMPAD8/NUMPAD2/NUMPAD4/NUMPAD6.
So you need to set up the retroarch mapping settings in core options accordingly.
Same for the other controls, refer to the game manual for the complete keys list.

**Comment by i30817** [comment]
Grim fandango has a weird tank control and inventory\item\use scheme. It's the main complaint about the game besides the rushed ending. If you think movement mapping is confusing wait until you realize how inventory item look\interact\grab are used 😂

**Comment by arnaullv** [comment]
Thanks for all your comments I will try to map controls through core settings, but will this break the controls for other scummvm games? I tried to do this in the past but I didnt succeed.. I will try harder...
In any cadf I'm not sure why retroarch scummvm core needs all this cusyomization and scummvm native android app, works out of the box, maybe there is some code which is different?

**Comment by spleen1981** [comment]
You should be able to save a different configuration for each scummvm playlist entry, check retroarch docs.
Regarding differences between core and standalone versions, the core runs inside the retroarch system, hence all interfaces are handled differently (libretro API) from the stand alone.

**Comment by i30817** [comment]
Honestly. The scummvm standalone controls are also hot trash in certain games of that era that were in a weird intermediate state between "wanted to be fully controller operated" and "was actually keyboard operated". Just try to play monkey island 4 in scummvm. The first puzzle is completely horrible because it requires control reconfiguration afaict. I don't have a controller so maybe the situation is better upstream with it though.

**Comment by spleen1981** [comment]
Assumed clarified, closing this.
