### ISSUE TITLE
CoMI - Audio hitch when interacting with items

### ISSUE THREAD

**Issue by WDeranged** [libretro/scummvm#47]
This is an issue I've seen with the Windows version but it's more severe here.  I'm running it through Retroarch with a pretty good pc.  I've tried running with all the low latency options disabled and buffer sizes increased but it doesn't make any difference.

Every minute or so I'll interact with an item and the game temporarily halts for split second before the animation or speech starts to play.

I've seen it happen in a few other games.  Usually ones with streaming background music rather than midi.

**Comment by spleen1981** [comment]
> This is an issue I've seen with the Windows version

Do you mean ScummVM stand alone version? If the issue is already there, needs to be fixed upstream, can't fix here.
It may be that the issue is more evident in the core, as audio/video streams are bounded to a certain frame rate, differently from the stand alone version.

**Comment by WDeranged** [comment]
Yes the standalone windows version sometimes has the same issue.  For whatever reason it happens far more with the libretro version.

**Comment by spleen1981** [comment]
Can you test this [build](https://git.libretro.com/libretro/scummvm/-/jobs/4609227/artifacts/download)?

**Comment by WDeranged** [comment]
> Can you test this [build](https://git.libretro.com/libretro/scummvm/-/jobs/4609227/artifacts/download)?

That is a huge improvement.  What changes did you make?  I still get hitches but now I think it's closer to the standalone release.

I made a few saves near locations I know cause hitches and most of them don't happen now.  It seems all the remaining hitches happen during dialogue rather than when interacting with something.

**Comment by spleen1981** [comment]
> What changes did you make?

It's some simplification and improvement in audio run loop, I will try to test more to avoid regressions on other engines before merge into master.
As we are close to standalone version, once merged we may close here, we can't fix engines issues core side.

**Comment by spleen1981** [comment]
cf30fe324f26f952bf2a8367b2f0eeaf3f7f1b8f and 3d5c3d7afa8b3f3518cc6330d5f1cc8a3eed080e are now merged to master
