### ISSUE TITLE
Quest for Glory 2 (AGDI/VGA) - Debug Menu Isn't Working

### ISSUE THREAD

**Issue by LupinePariah** [libretro/scummvm#50]
I've acquired the script files to activate the debug mode, and the frog ribbit sound effect plays at the start. F10 does nothing.

I've tested this in ScummVM standalone and it works.

Relevant links:

QFG2 (AGDI/VGA) - https://www.agdinteractive.com/games/qfg2/
Script Files - https://www.speedrun.com/qfg2vga/resources/tt4b2

The link provided to QFG2 isn't piracy, it's a fan remake.

Thoughts: Older versions of ScummVM didn't support later ACI versions properly. I saw reports of the ribbit sound playing but the F10 debug menu not showing there, but that was fixed some time ago in ScummVM standalone. I don't know if that is the issue here, but I figured I'd mention it.

**Comment by spleen1981** [comment]
What's this debug mode, an internal feature of this engine or you are referring to the the debug console (which can be accessed by default with `CTRL-Alt-d`)?
If it is an internal engine feature and you expect it to be activated by `F10`, be sure to set 'Game Focus' mode ON while trying, otherwise RetroArch mapping for F10 will prevail.

**Comment by LupinePariah** [comment]
Oh! I forgot to mention that. I was using game focus. That's via hitting ScrollLock, I believe? Yes. I mean, F5 would give me windowed mode instead of letting me save, otherwise.

It's actually a feature of the QFG2 remake itself. It's sort of a cheat mode that's unlocked by doing various things in the game, once you've done them, it unlocks the ability to utilise the battle and debug modes (F4 and F10 respectively).

It's interesting, because those modes are definitely activating (the ribbit plays at the start), but they're just not accessible. I wish I could provide something more than that, but I haven't really been able to figure anything else out.

Is there anything I should be looking for in the logs?

**Comment by spleen1981** [comment]
Tried the game at link above, and those mode are disabled I guess (maybe you can send a savefile where it's supposed to be activated).
Anyways you could test the [daily build](https://buildbot.scummvm.org/#/dailybuilds) for stand alone version to be sure it is not an issue upstream in current master.
It is strange that those keys, even if it's an hidden feature, are not mapped in ScummVM keymaps menu.
However engines for the core are compiled exactly same as stand alone version, so I don't expect any difference regarding  features included.

> That's via hitting ScrollLock

That depends on your configuration in retroarch

> Is there anything I should be looking for in the logs?

A retroarch log with DEBUG level set on both for core and frontend won't hurt

**Comment by gouchi** [comment]
@LupinePariah Any update ? Thank you.

**Comment by spleen1981** [comment]
Looks like a stale issue and not confirmed to be still valid or not. Feel free to reopen if needed.
