### ISSUE TITLE
ScummVM core crashing on Xbox Series X

### ISSUE THREAD

**Issue by solstice0** [libretro/scummvm#51]
When starting the core, the screen goes black for a bit then crashes to dev mode dashboard.

This core was working at one point, back on 1.15.0.

Log attached.

[retroarch (2).log](https://github.com/libretro/scummvm/files/14234062/retroarch.2.log)

**Comment by spleen1981** [comment]
Didn't even know the core was running on Xbox Series X, which build is used, windows one?
However the log does not say anything special, and the core is working ok on windows, so it must be something specific to Xbox Series X environment, which btw is not supported specifically and does not have a specific build recipe available.
Anyway is there any system crash log available somewhere in this platform?

**Comment by MrWrightyLC** [comment]
I can confirm that this is a UWP specific problem, fortunately using an old scummvm build has worked for me.

Btw, this problem originates between September and October 2023.
Since I am using a build from 09/16/23

**Comment by spleen1981** [comment]
> Since I am using a build from 09/16/23

Can you provide the exact working version (the one shown after 'Load core' in retroarch).

**Comment by spleen1981** [comment]
> I can confirm that this is a UWP specific problem

Just tested UWP build from retroarch site on Windows 10, and I'm able to reach ScummVM GUI with no issue.
Do you mean it's a specific problem of UWP running on Xbox only?

**Comment by MrWrightyLC** [comment]
Yes only happens in UWP (xbox series), to tell the truth I am not surprised that it is an incompatibility with some driver or something else exclusive to xbox uwp

**Comment by spleen1981** [comment]
Ok,
- Any way to get a system crash log on xbox?
- Is there a stand alone ScummVM version available to be tested? (preferably 'daily builds')
- Assuming the issue is in the core code (could be quickly verified with previous bullet), we could bisect to find the offending commit, if you are willing to test. Assuming that currrent master is not working, first test is [here](https://git.libretro.com/libretro/scummvm/-/jobs/4809853/artifacts/download).

**Comment by MrWrightyLC** [comment]
Same result with the artifact build
Load core and then run core it just crash
[retroarch(3).log](https://github.com/libretro/scummvm/files/14376132/retroarch.3.log)

> Is there a stand alone ScummVM version available to be tested? (preferably 'daily builds')

There is no standalone version for uwp xbox

**Comment by spleen1981** [comment]
test 2 [here](https://git.libretro.com/libretro/scummvm/-/jobs/4809972/artifacts/download)

**Comment by MrWrightyLC** [comment]
Again :/
[retroarch(4).log](https://github.com/libretro/scummvm/files/14378387/retroarch.4.log)

**Comment by spleen1981** [comment]
[test 3](https://git.libretro.com/libretro/scummvm/-/jobs/4810037/artifacts/download)

**Comment by MrWrightyLC** [comment]
Again crash

**Comment by spleen1981** [comment]
[test 4](https://git.libretro.com/libretro/scummvm/-/jobs/4810059/artifacts/download)

**Comment by MrWrightyLC** [comment]
Crash again, even now my old working core crashes too, anyway I have to get back to work.
tomorrow I might try again, still thanks for taking the time to create these builds.

**Comment by spleen1981** [comment]
If the version posted above as working is actually not working, we are wasting time bisecting...
Please confirm the version a56c2b83 is working or not...
If it was working with an old bundle and now is not working anymore with a more recent build of retrorch, then the bug has something to do with a retroarch update+scummvm core (maybe any version, you may check latest core+old bundle if it's working)+xbox environment.
In that case a system crash log would help.

**Comment by solstice0** [comment]
I can upload a .dmp file if needed

**Comment by spleen1981** [comment]
> I can upload a .dmp file if needed

Ok

**Comment by spleen1981** [comment]
@MrWrightyLC @solstice0 if you can test this [debug build](https://git.libretro.com/libretro/scummvm/-/jobs/4828470/artifacts/download) it may give a more verbose retroarch log (depending on where it crashes).
If you get any dump or crashlog with this version it could help as well.

**Comment by gouchi** [comment]
@MrWrightyLC @solstice0 Any update ? Thank you.

**Comment by spleen1981** [comment]
Looks like a stale issue and not confirmed to be still valid or not. Feel free to reopen if needed.
