### ISSUE TITLE
Update CHD to support ZSTD

### ISSUE THREAD

**Issue by Papermanzero** [libretro/scummvm#52]
https://docs.mamedev.org/tools/chdman.html#createraw

Mame 0.262 introduced zstd as data compression. It would be good to update to the newest chd version to use the benefits from zstd over zlib.

**Comment by spleen1981** [comment]
Chd format is not supported in scummvm, only plain game folders.
However it would be a topic for the main scummvm/scummvm repo upstream, but there is no intention to go that way afaik.

**Comment by Papermanzero** [comment]
I thought they already support it. It would be beneficial if they are going to implement it. With zstd the reading speeds are incredibl high and the compression has archive quality. Almost all emulation/simulation projects are using it .

it is even easy to implement it with this lib:
https://github.com/rtissera/libchdr
