### ISSUE TITLE
When selecting anything from the intial menu, libretro crash builtin theme global options

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/scummvm#53]
Description
-----------------
Launching scummvm opens right but when I try to select anyrthing in the start menu a game, global options, load whatever thing is displayed. Libretro unloads the core and it ends in Main Menu retroarch screen with no core selected. Scummvm extra menus are located in retroarch folder System.

So interacting with start menu unload the core

System
------------------
Odroid n2+ custom Emuelec 4.7 
Latest commit [d8610590364fde127fbd4dae4c4a0447394d8daa](https://github.com/libretro/scummvm/commit/d8610590364fde127fbd4dae4c4a0447394d8daa)
RetroArch 1.18 latest commit https://github.com/libretro/RetroArch/commit/f5498759534b81b867fcb27262f1f160357f425f
Pad Xbox 360 pad

Expected behaviour.
------------------
Be able to interact with anything in the screen, select a game, open global options, load a gram, click on about.

Troubleshoot
-------------------
I don't see any crash. Per Retroarch logs it seems it is unloading the core... just it.
[retroarch.log](https://github.com/libretro/scummvm/files/14759803/retroarch.log)

Repo
---------------
Open scummvm libretro
Select any item in the menu about, load , options etc or select a game it will unload the core

**Comment by spleen1981** [comment]
Looks like regular shutdown from log. You also got a warning that game pointed by selected .scummvm file cannot be found, check its content or use the embedded playlist generator. 
Are you using retropad 'L' button to select? Note that 'A' button is mapped as 'keyboard ESC' by default. You can change mappings in core options.

**Comment by Kelvfimer** [comment]
@spleen1981 I'm a lamer Sorry for the stupid question, yes that was causing the unloading. 

Now that I know that selecting global options I get an error. The theme is the builtin green and darkk I have the extra folder with the themes.

[libretro ERROR] Unable to load widget position for 'GlobalOptions_Backend_Container.Container'. Please check your theme files for theme 'builtin'!

log file

[retroarch.log](https://github.com/libretro/scummvm/files/14762776/retroarch.log)

But I don't see any builtin theme.

thx for your support

**Comment by Kelvfimer** [comment]
Ok solved. I added the extra folder in the wrong path.

thx for your support

**Comment by spleen1981** [comment]
If that error persists you can try to download again scummvm core system files, local ones could be corrupted or outdated.
