### ISSUE TITLE
Can't launch Scummvm core at all on N3DSXL

### ISSUE THREAD

**Issue by AngeryCinnabon** [libretro/scummvm#56]
When I try to load the latest version of the core (on both .3dsx and .cia builds) my 3ds immediately crashes with this error. it can be recreated by installing RA and the Scummvm core. I've tried going back to the oldest available nightly and stable builds but both have the same issue
![20240418_214927](https://github.com/libretro/scummvm/assets/24904313/bb2e2e8c-cf51-41ba-9e67-f58f92166336)
Here is my Luma3DS crash dump as well.
[crash_dump_00000001.dmp](https://github.com/libretro/scummvm/files/15032097/crash_dump_00000001.dmp)

**Comment by spleen1981** [comment]
what was last working version? can you share a retroarch.log?

**Comment by AngeryCinnabon** [comment]
The last working version is the one packaged in 1.14.0 of the 3ds stable build, Scummvm 2.1.1. As for a log, here it is. 
[retroarch.log](https://github.com/libretro/scummvm/files/15044930/retroarch.log)

**Comment by spleen1981** [comment]
Can you set log level to DEBUG for both frontend and core from retroarch options?
> When I try to load

The core crashes when you load the core from retroarch or when you start it?

**Comment by AngeryCinnabon** [comment]
Sorry but something came up, I'll be away from my 3ds for a bit...so I'm gonna close this issue for now.
