### ISSUE TITLE
Request: allow building with chosen GL/GLES flags 

### ISSUE THREAD

**Issue by cmitu** [libretro/scummvm#57]
Hi,

 the recently added OpenGL HW renderer option and corresponding build flags are great for 3D games in ScummVM. One thing that could be improved would be the selection of which HW renderer context to be requested/used by the core. Right now, if I'm reading correctly the libretro backend _Makefile_, the choice is dictated by the `platfom` parameter passed on to `make`.

 It would be beneficial to allow overriding of the _HAVE_GL_ flags so that for platforms unknown/not configured in the _Makefile_ the correct HW renderer can be selected during build. I.e. to allow building for a Raspberry Pi5/Orange Pi5 with `make HAVE_MT32=1 HAVE_OPENGLES2` when RetroArch is built also with GLES3/GLES2 support.

**Comment by spleen1981** [comment]
would https://github.com/libretro/scummvm/commit/a89a0a986eb6249307df19e61f662a7c78d6a053 do the job?

**Comment by cmitu** [comment]
@spleen1981 Yes, I think that's ok. I'm building now with `FORCE_OPENGLES2=1` and OpenGLES2 is used during the build, whereas before it was defaulting to OpenGL (inherited from the `unix 64bit` platform).
Thank you for the changes, when they're added to the `master` branch, then I'll integrate the build options into our [package script](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/libretrocores/lr-scummvm.sh).

**Comment by spleen1981** [comment]
https://github.com/libretro/scummvm/commit/3df20dd9c6d2d9bba7e5af221c8f3ace53b1cd4f merged to master
