### ISSUE TITLE
Full screen/windowed mode toggle leads to black screen on Linux

### ISSUE THREAD

**Issue by heldderarbeit** [libretro/scummvm#60]
Load Core -> ScummVM -> Start Core from windowed Mode: ScummVM GUI is correctly rendered in a window, but if you press F key you get a black screen in fullscreen mode. If you press F again, you get a black screen in a window

[Screencast from 2024-07-30 06-31-45.webm](https://github.com/user-attachments/assets/5184fbe6-41a8-4128-8806-db491400d4f6)

Load Core -> ScummVM -> Start Core from fullscreen mode: ScummVM GUI is correctly shown in in fullscreen mode, but if you press F key you get a black screen in a window

If you move the mouse a white rectangle appears inside the black screen.

![Screenshot from 2024-07-30 06-16-27](https://github.com/user-attachments/assets/faefb125-b5b4-4a6c-a196-c4be5d00db4a)

This is the only core where I've seen this behaviour. At least in Dosbox-pure, the both N64 cores and Snes9x the toggle between fullscreen and windowed mode is working as expected.

System is Arch and RetroArch 1.19.1 from Flathub.
This bug occurs on:
Gnome X11
Gnome Wayland
Plasma X11
Plasma Wayland

Running ScummVM 2.8.1 from Flathub directly does not have this problem (Here toggling between fullscreen and windowed mode with Alt + Enter is working just fine). 

[retroarch.log](https://github.com/user-attachments/files/16422119/retroarch.log)

**Comment by gouchi** [comment]
I reproduce also this issue on X11 with RA from source.

**Comment by spleen1981** [comment]
Does it work if the core is started with the GUI already in full screen mode?

**Comment by gouchi** [comment]
@spleen1981 Yes, the issue also happens when the core is started with the GUI already in full screen mode.

**Comment by spleen1981** [comment]
Hi, can you check [this build](https://git.libretro.com/libretro/scummvm/-/jobs/5749842/artifacts/download)?

**Comment by gouchi** [comment]
@spleen1981 Thank you, I don't get the black screen anymore.

@heldderarbeit Is it ok for you using [this build](https://git.libretro.com/libretro/scummvm/-/jobs/5749842/artifacts/download) ? Thank you.

**Comment by heldderarbeit** [comment]
Yes, I can confirm that the updated scummvm_libretro.so no longer has the issue.

**Comment by spleen1981** [comment]
fixed by b7c2e361b2745dd71190cbc4dd257b231f7d4a50
