### ISSUE TITLE
Scumm games cursor glitch

### ISSUE THREAD

**Issue by Urthaug78** [libretro/scummvm#61]
When hit F1 to enter Retroarch menu and then leave the cursor become glitchy. This only affect Lucas games. Tried under various 2.9.0 builds including the last 4f5f776b.

Retroarch version 1.15.0.

**Comment by Urthaug78** [comment]
The FM-Towns versions are not affected by this behaviour.

**Comment by gouchi** [comment]
> Retroarch version 1.15.0.

May you try with latest stable which is 1.19.1 ?

Thank  you.

**Comment by Urthaug78** [comment]
Just tried with 1.19.1 and the problem is not present...

**Comment by gouchi** [comment]
So please close this issue, if you don't reproduce it.

Thank you.

**Comment by Urthaug78** [comment]
Closed.
