### ISSUE TITLE
Buildbot does not compile new versions

### ISSUE THREAD

**Issue by ToniBC** [libretro/scummvm#7]
Hello, it's not that it's a bug as such, but since January 4, the news or advances are not compiled, the core is not updated and we cannot test things. Now that we have the core updated, at least to the stable one, which would be nice if it was nightly, but that's fine, we can't test it.

This is normal because it is updating or due to a compilation error. More than anything because other times it has already happened with other cores and as always, you have to warn them. xd

Thanks for updating the core.

**Comment by ner00** [comment]
Yes, it seems that the buildbot is still building from the legacy core repo: https://github.com/libretro-mirrors/scummvm

I hope this gets fixed at least in time for the next RetroArch release, but hopefully sooner.

**Comment by spleen1981** [comment]
it is being worked on

**Comment by spleen1981** [comment]
new core is online now.

> Now that we have the core updated, at least to the stable one, which would be nice if it was nightly

@ToniBC the idea is to have a libretro core aligned with official upstream releases, if you like to test against upstream master you can build `2.7.0-git` branch (and update submodule reference commit as needed).
