### ISSUE TITLE
Retroarch minimize bug when starting the game

### ISSUE THREAD

**Issue by KamiLordus** [libretro/scummvm#70]
After the latest update, a strange problem appeared. Before launching some games (for example Prince and the Coward), Retroarch minimizes 2 times, instead of 1.
The problem did not occur in the previous version of scummvm 2.9.2

**Comment by spleen1981** [comment]
Not very clear what do you mean by minimize... Any other game affected?
Can you share a retroarch.log?

**Comment by KamiLordus** [comment]
It's a bit hard to explain. If necessary, I can record a short video that will illustrate this bug.
It's about Retroarch's behavior just before starting a given game.
Retroarch minimizes itself to the Windows bar, then returns to full screen and the game starts. Due to a bug, it does this TWICE for many games. Probably those that use higher resolution.
I'll just add that an identical bug was in the case of the MAME core in Retroarch a long time ago. It was about changing the geometry. Unfortunately, I don't know the details.

Other games with the same problem include:
Bizzare Adventures of Woodruff
Blade Runner
Broken Sword - Shadow of the Templar
Broken Sword 2
Broken Sword 2.5
Curse of Monkey Island
And probably much, much more

[retroarch.log](https://github.com/user-attachments/files/17529429/retroarch.log)

**Comment by spleen1981** [comment]
It should be fixed in latest master @ 207a65c8eb9a186b74f4cd0283ca5b388e952815

**Comment by KamiLordus** [comment]
I have tested all the previously mentioned games and they all run without any problems. Thanks for the fix.
