### ISSUE TITLE
2 For 1 Issue.  Blackwell Deception runs incredibly slow on lower spec hardware/Scratchy Speech with Talkie Monkey Island 1/2

### ISSUE THREAD

**Issue by KMFDManic** [libretro/scummvm#75]
I have tested compiling for a few different platforms.  Most games run absolutely fine, with the FPS perimeter helpful on more stubborn ones like Blade Runner.  But, Blackwell Deception seems to be the single worst running game I have tested thus far.  Not sure if there is anything that can be done about this particular game?  The Blackwell Deception Demo is easily available for download and testing.  I am personally running it on platforms that range from 1.008 Ghz-1.53 Ghz.  Blade Runner previously would only work without stutter, if I enabled frameskipping.  But, the FPS change helped it, as well.  Blackwell Deception seems to be another potential solution needed.   

And, for some reason, have been getting garbled, scratchy, indecipherable speech when trying to run Talkie versions of Monkey Island 1/2.  Maybe, there is a flag or dependency I am missing for this?  As an example, compiling it for, platform=miyoomini

Thanks in advance for any insight.  Let me know if any more information is needed.  Can do compiles if need be to test any variables that may fix either or with the perimeters I outlined.  Thanks again!

**Comment by spleen1981** [comment]
can you share a retroarch log for both issues, debug level set both for frontend and core

**Comment by KMFDManic** [comment]
@spleen1981 Bit of a doh moment, as ive used retroarch logs to debug previously with other cores. Didn't even think to check there first. I will drop a log within next day or so (have work and being battered with blizzard weather:(, and greatly appreciate your insight in advance on helping fix these 2 issues. Thanks!  Will follow up soon!

**Comment by KMFDManic** [comment]
@spleen1981 The latest commits you did actually fixed the sound issue on my end:)  Thanks so much for that.  I compiled from fairly recently, as a secondary test...And, the sound didn't work properly there.  Works flawlessly now:)  Blackwell Deception also runs a bit better than in recent builds.  Thanks again!  You Rock:)

**Comment by spleen1981** [comment]
I think I can close this. In general what you can do core-side to improve performance on low-end devices is to set the Framerate Cap to a low value and  samplerate to 44100 (and disable all extra stuff like MT32 of course).
Other frontend level settings may halp, like the Threaded Video one.
