### ISSUE TITLE
[WiiU] Issues Loading Games From Either Load Content or From the Scummvm UI

### ISSUE THREAD

**Issue by Ploggy** [libretro/scummvm#8]
Hi I've been testing this new Scummvm on WiiU to see if it has fixes the seg fault issue we we're having with the old Core.
The earlier Scummvm had issues on WiiU whenever I tried to choose a Directory from within the Scummvm UI, it would crash the Core with a segfault error (there was an issue made awhile back but it looks like the issues haven't carried over from the older Scummvm Core.)
The good news is the segfault error when I try to choose a directory is fixed! :^)

But now I can no longer get a game (in this case Kings Quest 7) to load.
If I try to load the game from Load Content, by loading a KQ7.scummvm file directly it will seg fault. same if I try to load the games exe.
![20230108_230901](https://user-images.githubusercontent.com/1160255/211223731-7089fb7d-91b8-4ec2-a903-725ee89674df.jpg)
If I try to add the game from within the Scummvm UI I can get as far as selecting the games directory but when I choose the directory it will show a big list of possible games to chose from
![20230108_232219](https://user-images.githubusercontent.com/1160255/211224189-d38a2598-2b8c-4d16-9f54-7253658149ab.jpg)
but if I select King's Quest VII: The Princeless Bride (Windows/English) - Unknown Variant it will say it seems to be an unknown variant and wont allow me to add the game.
![20230108_232511](https://user-images.githubusercontent.com/1160255/211224245-489036b3-ab6b-4a2b-9fbe-67d15f63acf3.jpg)
Doing the same process on the PC version of the Core will only show only the Kings Quest 7 game in the list and wont have the unknown variant tag and will add the game correctly..

Also I've tried adding the Hi-Res Adventure 1 - Mystery House game from the Content Downloader, but when I try to add that game it says "ScummVM could not find any game in the specified directory!" again this works fine on the PC version of the Core.

Thank You.

EDIT:
I've even gone as far as copying over the Scumvm.ini from the PC to the WiiU (first editing the game path to match the games location on my sd card) so the game is pre-added to the ScummVM UI, but loading the game then says "Error running game: Game data not found" :P

**Comment by spleen1981** [comment]
- So in your first attempt you launched the `.scummvm` file without any game id correspondance in `scummvm.ini` and you got segfault right? That would be a separated issue in case.
- Regarding kq7, actually those hashes are not detected by the engine (ref [here](https://github.com/scummvm/scummvm/blob/4bf45d922baaf68552c9936491d34361ffb467f2/engines/sci/detection_tables.h#L2283)). Can you manually check the MD5 of those two file?
- Is the core working with other engines/games?

**Comment by Ploggy** [comment]
Yes, I've now tried loading King's Quest 7 and Hi Res Adventure - Mystery House to load through Retroarch's Load Content and they will segfault if loading the games exe directly.
I have managed to get Secret of Monkey Island to boot through the Monkey.scummvm file but when it does boot it says:
![20230109_134216](https://user-images.githubusercontent.com/1160255/211322159-91e9234a-5ce2-47cb-a8e6-2fef18d4ccb1.jpg)
If left on that screen for a couple minutes then it will segfault:
![20230109_134727](https://user-images.githubusercontent.com/1160255/211322898-fe7ff291-9cfe-46ff-af94-52d080d9f720.jpg)

I have also managed to get Secret of Monkey Island to add through the ScummVM UI, but loading the game through the UI will show the same screen as above:
![20230109_134216](https://user-images.githubusercontent.com/1160255/211322159-91e9234a-5ce2-47cb-a8e6-2fef18d4ccb1.jpg)
I get the feeling the WiiU Core is being far more picky of which game to boot than the PC Core.

KQ7, Looks like the hash of my version of the game doesn't match any listed on the ref page :/ Still strange how it is able to be added fine on PC Core ScummVM?

So far I haven't got any games to load. but again all the games I've used to test add and work fine on the PC Core.

**Comment by spleen1981** [comment]
Just to be sure you may check with current master.
Did you check manually the MD5 of the files above (those actually stored in the console)? Are the same prompted by ScummVM? If unknown MD5 is confirmed, those could have been corrupted somehow, and it should not work even on windows version (which I assume to be v2.6.1 as well).
Also you may try with one of the [freeware games](https://www.scummvm.org/games/) from scummvm website to check if the core works.

**Comment by Ploggy** [comment]
I've tested with the latest master but the issues are the same.

Strange, looks like the md5 hashes are different? ScummVM UI sees them as:
![20230111_191439](https://user-images.githubusercontent.com/1160255/211898152-f5962f39-1191-447a-87e1-6bab277d51c2.jpg)
Where as if I manually check md5 they show as:
Resource.000 - acfbbf1d69d1d859c3c5072e03e30f3d
Resource.map - e73c01ca97deadc2ecb85e3e43c20477
None of the md5 hashes above match with any on the ref page:
https://github.com/scummvm/scummvm/blob/4bf45d922baaf68552c9936491d34361ffb467f2/engines/sci/detection_tables.h#L2283
I haven't found any version of the game that matches any of those ref md5.

I have tested adding this exact same game on the newest PC version v2.6.1 too and it adds and starts perfectly.

I have tried one of the freeware games from the link you provided on the WiiU v2.6.1
Beneath the Steel Sky - Adds fine but when I boot the game:
![20230111_193533](https://user-images.githubusercontent.com/1160255/211902101-1235c720-c0a0-4696-a580-6b6a5358e388.jpg)
Works on PC v2.6.1

**Comment by ner00** [comment]
> Where as if I manually check md5 they show as:
> Resource.000 - acfbbf1d69d1d859c3c5072e03e30f3d
> Resource.map - e73c01ca97deadc2ecb85e3e43c20477
> None of the md5 hashes above match with any on the ref page:

Are you calculating the MD5 hashes based on the first 5000 bytes or less? ScummVM uses this approach for performance reasons. More here: https://wiki.scummvm.org/index.php/Reporting_unknown_MD5_checksums

**Comment by Ploggy** [comment]
No I've been calculating the md5 of the entire file using this site:
https://emn178.github.io/online-tools/md5_checksum.html

**Comment by Ploggy** [comment]
OK looks like one of my games does indeed match with one on the ref list.

**2be9ab94429c721af8e05c507e048a15**  C:\Users\Susan\Desktop\md5deep-4.4\RESOURCE.MAP offset 0-4999
Matches:
// King's Quest 7 - English Windows (from the King's Quest Collection)
	// Executable scanning reports "2.100.002", VERSION file reports "1.4"
	{"kq7", "", {
		{"resource.map", 0, "**2be9ab94429c721af8e05c507e048a15**", 18697},
		{"resource.000", 0, "eb63ea3a2c2469dc2d777d351c626404", 203882535},
		AD_LISTEND},
		Common::EN_ANY, Common::kPlatformWindows, ADGF_NO_FLAGS, GUIO_KQ7 },
Excellent :) but it doesn't explain why the game is recognised perfectly on PC but not on WiiU?

**Comment by spleen1981** [comment]
The two screenshots above for KQ7 are done with different sets? MD5 and sizes are different.

**Comment by Ploggy** [comment]
Yes, I was on a quest to find a version of the game that would add through the ScummVM UI or match the ref page.. Now I have the King's Quest Collection version, that's the version that matches with the ref page. :)

**Comment by spleen1981** [comment]
So the hash calculated by the core it's confirmed to be different by the one calculated manually?

**Comment by Ploggy** [comment]
Yes, the Core ScummvM UI md5 shown on WiiU is different from the hash from the reference page (which its confirmed to be the King's Quest Collection edition) or if I check manually using md5deep.exe suggested by the link that ner00 posted.

**Comment by spleen1981** [comment]
and same crash launching Beneath a Steel Sky? 
Just to be sure, did you clone at this commit https://github.com/libretro/scummvm/commit/7bf21109c2f2fa60e6b46181860c528378d5206d?

**Comment by Ploggy** [comment]
Yes same crash as before with Beneath the Steel Sky. 
![20230111_193533](https://user-images.githubusercontent.com/1160255/211902101-1235c720-c0a0-4696-a580-6b6a5358e388.jpg)
Yes, The "makefile: add SCUMM_BIG_ENDIAN to wiiu" commit.

**Comment by spleen1981** [comment]
Was the legacy core working with any game on wiiu?

**Comment by Ploggy** [comment]
The old Core used to load games from a .scummvm file.. but whenever I tried to add a game from the ScummVM UI it used to segfault when we selected "Choose" directory.. I could never get Kings Quest 7 to boot even with the old Core.

**Comment by spleen1981** [comment]
So Beneath the Steel Sky, just to have a reference, was running on the old core? Or any other specific game?
I'm asking to understand if there is a regression with new core (that would be easier to investigate) or if it never worked.
Basically to understand if we have a regression we should do the same actions (successfully) on the old core and (unsuccessfully) on the new one.

**Comment by Ploggy** [comment]
Beneath the Steel Sky boots fine if loaded with the sky.scummvm file from Load Content
Loading the sky.dsk file from Load Content it will blackscreen.

and since Beneath the Steel Sky was already added in the latest version, loading the game from the older Core boots fine too :p 
I would say there's a regression. :)

**Comment by spleen1981** [comment]
> Beneath the Steel Sky boots fine if loaded with the sky.scummvm file from Load Content Loading the sky.dsk file from Load Content it will blackscreen.

this happens with current master?

**Comment by Ploggy** [comment]
No, sorry I should have specified, that's what happens with the old Core.

**Comment by spleen1981** [comment]
I've added new fixes in the `wiiu` branch, can you test it?

**Comment by Ploggy** [comment]
Sure I'll test but I can't build the Core myself, I've been grabbing the artifact from the gitlab page, I can usually grab it an hour or 2 after you make a commit to master.

**Comment by Ploggy** [comment]
oops I mean main, you need to commit it to the main branch before it can appear on the gitlab page :)

**Comment by Ploggy** [comment]
Awesome! Both Beneath the Steel Sky and Secrets of Monkey Island both boot fine from their .scummvm files. YAY!
Kings Quest 7 does boot from it's .scummvm file too but it seems to freeze on a black screen for a min then continues to boot the game, then shows an error: 
"Fluidsynth requires a 'soundfont' setting. Please specify it in the ScummVM GUI MIDI tab. Music is off" 
I think it's just a matter of messing with the settings tho :)
it also now add's just fine through the ScummVM UI too. So GOOD! 
I'm going to mess with it some more and see if i can get it to continue to in game. Thank you soo much for this. The Core now is better than the old core for sure!

I'll msg back here if all goes well.. or not :P

ThankYou!

**Comment by spleen1981** [comment]
> "Fluidsynth requires a 'soundfont' setting. Please specify it in the ScummVM GUI MIDI tab. Music is off"

You need to select [this file](https://github.com/libretro/scummvm/blob/main/dist/Roland_SC-55.sf2) in the gui settings as soundfont.

**Comment by Ploggy** [comment]
OK I set up soundfont and set the audio to fluidsynth, the game does boot now (still takes over 60 secs to boot) but it does eventually get to the KQ7's menu, but when I try to enter my name I get a segfault:
 ![20230113_003443](https://user-images.githubusercontent.com/1160255/212210250-56160c05-4b26-4d50-8843-5f47b08be2f3.jpg)
The game does run a little slow though and audio is stuttering abit.. I never got the King's Quest 7 in game before so I don't know if it's a limitation of the WiiU of a problem with the Core :P

The WiiU should run the game ok right?
I'll try setting the Speed Hack option in the Core's Options and see if it makes a difference :)

**Comment by Ploggy** [comment]
I set the audio from fluidsynth back to default to see if it stops the crash but it still segfaults the same as before, the speed hack setting did seem to help some but its still below fullspeed.

**Comment by Ploggy** [comment]
Good news! I got a different version of King's Quest 7 and it now gets in game :) 
I've enabled Retroarch's FPS counter, I'm getting 44.96FPS its not great but it is playable since its a point + click game :) the only downer is the skipping audio, does Scummvm have a frame skip option? or some other way of increasing speed other than the Speed hack option in the Core options?

**Comment by Ploggy** [comment]
A video showing performance of KQ7 on WiiU. 
https://streamable.com/gw28xi

**Comment by spleen1981** [comment]
can you check if latest commit in `wiiu` branch improves the performance?

**Comment by Ploggy** [comment]
Sure thing, as soon as the artifact gets made I'll test it :)

**Comment by Ploggy** [comment]
No, performance is the same as the last build. I've tried changing audio/graphic settings in the ScummVM UI but nothing I do seems to effect performance.

**Comment by spleen1981** [comment]
Ok I think that's a good result anyways, considering that wiiu is not even supported upstream.
Can you test again last commit in `wiiu` branch before merging to main, I did some code cleaning.

> does Scummvm have a frame skip option

Nope

> or some other way of increasing speed other than the Speed hack option in the Core options?

You may try enabling the "Threaded Video" option in retroarch video settings.

**Comment by Ploggy** [comment]
OK, everything seems the same as before. Even if this is as fast as it gets, the fact that Kings Quest 7 is working at all is a big bonus for me :) So thank you for that.. I've been hoping to get this on WiiU since the WiiU RA port happened, I've tried running KQ7 on the Dosbox/Pure Core but it runs even slower on that lol due to lack of Dynarec. 

WiiU doesn't have a Threaded Video option in Retroarch. 

Everything looks good here if you want to merge, and thanks again for looking at this, the Cores in a much better state than it ever was :)

**Comment by LibretroAdmin** [comment]
Hi @MrHuu or someone else who is involved with teh 3DS RetroArch Port,

could you guys try the latest ScummVM core for 3DS on the buildbot and tell us how it compares to the old one? It's based on this latest rebased version by @spleen1981 and we are eager to learn if things have not regressed on the low end side of the platform spectrum. Thanks!

**Comment by spleen1981** [comment]
> Hi @MrHuu or someone else who is involved with teh 3DS RetroArch Port,
> 
> could you guys try the latest ScummVM core for 3DS on the buildbot and tell us how it compares to the old one? It's based on this latest rebased version by @spleen1981 and we are eager to learn if things have not regressed on the low end side of the platform spectrum. Thanks!

ok, closing this in the meanwhile as completed
